### ISSUE TITLE
Create RIT logo with transparent background and more horizontal width

### ISSUE THREAD

**Issue by justwheel** [FOSSRIT/knowledgebase#4]
In #3, @robellegate fixed the logo and it now appears on the site. But I forgot @ct-martin pointed out the official RIT orange changed at some point, and now that difference is now obvious on the home page.

So, creating a more attractive web version of the RIT logo that appears in the header, and then replacing that here on the site source would be a nice user experience improvement.

**Comment by ct-martin** [comment]
RIT Brand Portal: https://www.rit.edu/marketing/brandportal/

Contains the requirements for RIT logo usage, colors, typeface (fonts), sizing, spacing around the logo, etc. Specifically of interest to you will be anything under "Brand Elements" and "Toolkits > Logos"

You will also need to consider given the distinctions you've made in [the runbook](https://runbook.fossrit.community/about/contact/) between FOSSRIT and FOSS@MAGIC whether the FOSSRIT website is even allowed to use official RIT branding (insert standard "I am not a lawyer" clause here).

There are three classes of RIT identity that could apply based on the "Brand Elements > Our Identity" flowcharts:
* If FOSSRIT is officially part of FOSS@MAGIC, the RIT or MAGIC logo should still be used
  * Pros:
    * Can definitively use the RIT branding
  * Cons:
    * No "FOSS" in the logo itself
    * Will probably look about the same as the existing logo
* If FOSSRIT is a "sponsored entity" (like an official student club, which are endorsed by Student Government iirc), you're allowed to use RIT within the logo
  * Pros:
    * Can use a custom logo with RIT in it
  * Cons:
    * Have to get logo approved by marketing
* If FOSSRIT is neither officially part of FOSS@MAGIC nor a "sponsored entity", you'll lose the official branding
  * Pros:
    * Freedom to do what you want for the logo
  * Cons:
    * Will likely have to change the description of FOSSRIT across website, GitHub, runbook, etc. to say that FOSSRIT is unofficial
    * Will be ineligible for official branding

Since FOSSRIT is defined in the runbook as not separate from FOSS@MAGIC (and also not under FOSS@MAGIC), unless SJ has done paperwork to make FOSSRIT (as "FOSSRIT" itself; not "FOSS@MAGIC") an official "sponsored entity," you are likely the last case.

I know some people within FOSSRIT have made clear that they aren't picky about following RIT's rules when it suits them, but since you're considering changing the logo (which falls under those rules), I think it's necessary (since while I am neither taking on this change nor responsible for FOSSRIT,  I do identify with it, have been mentioned here, and am providing information about the RIT branding) that I should at least inform you that there are these conditions which will affect what you're allowed to do with the logo.

**Comment by robellegate** [comment]
> In #3, @robellegate fixed the logo and it now appears on the site. But I forgot @ct-martin pointed out the official RIT orange changed at some point, and now that difference is now obvious on the home page.
> 
> So, creating a more attractive web version of the RIT logo that appears in the header, and then replacing that here on the site source would be a nice user experience improvement.

When I was working at ITS we were joking about creating a REST API to get the current color pallet from the brand portal since it was changing so often.

**Comment by justwheel** [comment]
> You will also need to consider given the distinctions you've made in [the runbook](https://runbook.fossrit.community/about/contact/) between FOSSRIT and FOSS@MAGIC whether the FOSSRIT website is even allowed to use official RIT branding (insert standard "I am not a lawyer" clause here).
>
> I know some people within FOSSRIT have made clear that they aren't picky about following RIT's rules when it suits them, but since you're considering changing the logo (which falls under those rules), I think it's necessary (since while I am neither taking on this change nor responsible for FOSSRIT, I do identify with it, have been mentioned here, and am providing information about the RIT branding) that I should at least inform you that there are these conditions which will affect what you're allowed to do with the logo.

Understood @ct-martin. This repo is neither for FOSSRIT or FOSS@MAGIC. It is proof-of-concept resource for an Open Source Program Office at RIT. This site is not official yet and this repo might be migrated to a different organization or entity on campus at some point. But it will be beyond the time I am employed at RIT. I put this repo in FOSSRIT because I didn't have anywhere else better to put it yet.

**Comment by ct-martin** [comment]
In the event that the Open Source Program Office is created and this site is used, RIT will presumably create a "lockup" logo for it (like the ones it has for the different colleges and MAGIC). If you want to plan for the future now, you can expect that it will be designed for a white background and [this logo variant (ZIP)](https://www.rit.edu/marketing/brandportal/downloads/logos/1505/collapsed-orange-black-08232019.zip) will likely be the closest you'll get to what will be given (inc. in size and colors). You can also use CSS `margin`s if you need a bit more space around the logo and don't want to change it directly.

Based on a couple guesses of what's happening (since I haven't been at FOSS Hours and am not otherwise keeping up to date, nor do I have time to), I think the best choice for now would be to use the logo linked above (which also has an SVG version), and mark this issue as blocked until where this site lives under is decided, because that will determine what logo(s) can be used.

I'm going to be unsubscribing from this issue since I'm not involved in doing this. I guess you can @-mention me if you need anything (that said, the brand portal website should be able to answer anything I can think of if you read enough of it)
